### ISSUE TITLE
events.js:165  // Unhandled 'error' event - Error: connect ECONNREFUSED 127.0.0.1:36131

### ISSUE THREAD

**Issue by Antoinebr** [Antoinebr/docker-google-lighthouse-express#1]
```
Error: Error: Command failed: lighthouse --enable-error-reporting --chrome-flags="--no-sandbox --headless --disable-gpu" https://www.santanderconsumer.se/ --output-path=/home/chrome/reports/www.santanderconsumer.se_2019-03-07__20-30-48.blocked --output json --output html --blocked-url-patterns=facebook.net --blocked-url-patterns=hotjar.com --blocked-url-patterns=google-analytics.com --blocked-url-patterns=googletagmanager.com --blocked-url-patterns=adservicemedia.dk 
Thu, 07 Mar 2019 20:30:48 GMT ChromeLauncher Waiting for browser.
Thu, 07 Mar 2019 20:30:48 GMT ChromeLauncher Waiting for browser...
Thu, 07 Mar 2019 20:30:48 GMT ChromeLauncher Waiting for browser.....
Thu, 07 Mar 2019 20:30:49 GMT ChromeLauncher Waiting for browser.....[32m✓[0m
Thu, 07 Mar 2019 20:30:50 GMT status Initializing…
Thu, 07 Mar 2019 20:30:50 GMT status Loading page & waiting for onload Scripts, CSSUsage, Viewport, ViewportDimensions, ThemeColor, Manifest, RuntimeExceptions, ChromeConsoleMessages, ImageUsage, Accessibility, AnchorsWithNoRelNoopener, AppCacheManifest, Doctype, DOMStats, JSLibraries, OptimizedImages, PasswordInputsWithPreventedPaste, ResponseCompression, TagsBlockingFirstPaint, WebSQL, MetaDescription, FontSize, CrawlableLinks, MetaRobots, Hreflang, EmbeddedContent, Canonical, RobotsTxt, Fonts
Thu, 07 Mar 2019 20:31:35 GMT Driver:warn Timed out waiting for page load. Moving on...
Thu, 07 Mar 2019 20:31:35 GMT statusEnd Loading page & waiting for onload
Thu, 07 Mar 2019 20:31:35 GMT status Retrieving trace
Thu, 07 Mar 2019 20:31:35 GMT status Disconnecting from browser...
Thu, 07 Mar 2019 20:31:35 GMT ChromeLauncher Killing Chrome instance 11045
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:36131
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)
Emitted 'error' event at:
    at Socket.socketErrorListener (_http_client.js:395:9)
    at Socket.emit (events.js:180:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:178:19)
```

**Comment by Antoinebr** [comment]
Fixed by bc60e21
